<?php

	// globals
	date_default_timezone_set('America/Los_Angeles');

	// imports
	include 'assets/php/my/common.php';

	// connect to database
	require('assets/php/my/mysql_db.php');
	$mysql_host = 'localhost';
	$mysql_database = 'sundaysc_trigger';
	$mysql_user = 'sundaysc_php';
	$mysql_password = 'Bismillah&';
	$DB = new mysql_db();
	$connectid = $DB->sql_connect($mysql_host, $mysql_user, $mysql_password, $mysql_database);

	// http_response_code(301);
	// header('Content-Type: application/json');
	// header('Content-Type: text/html');
	$ojson = array();

	$confirm_id = $_GET['confirm_id'];
	if (is_null($confirm_id)) {
		$ojson['error'] = '`confirm_id` not provided';
		// print json_encode($ojson);
		$redirurl = 'http://127.0.0.1/trigger-app?page=purchase&error=confirm_id';
		header('Location: ' . $redirurl);
		// print '<script>setTimeout(function(){window.location.href="'. $redirurl .'"}, 5000)</script>Redirecting in 5 seconds...';
		exit();
	}

	$query1 = $DB->query('SELECT * FROM paypal WHERE confirm_id="'. $confirm_id .'"');
	// $ojson['$DB->get_num_rows()'] = $DB->get_num_rows();

	if ($DB->get_num_rows() == 0) {
		$ojson['error'] = 'The generated serial for this purchase was already claimed.';
		// print json_encode($ojson);
		$redirurl = 'http://127.0.0.1/trigger-app?page=purchase&error=already_claimed';
		header('Location: ' . $redirurl);
		// print '<script>setTimeout(function(){window.location.href="'. $redirurl .'"}, 5000)</script>Redirecting in 5 seconds...';
		exit();
	}

	$row = mysql_fetch_assoc($query1);
	$access_token = $row['access_token'];
	$time = $row['time'];
	$mac_hash = $row['mac_hash'];
	$buy_qty = $row['buy_qty'];
	$execute_url = $row['execute_url'];

    $payerid = $_GET['PayerID'];

    // execute the payment
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $postfields = array(
        'payer_id' => $payerid
    );

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $execute_url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postfields));
    curl_setopt($ch, CURLOPT_POST, 1);

    $headers = array();
    $headers[] = "Content-Type: application/json";
    $headers[] = "Authorization: Bearer " . $access_token;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    $httpstatus = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close ($ch);

    // print '$payerid: ' . $payerid;
    // print '$httpstatus: ' . $httpstatus;
	// print($result);

    if ($httpstatus == 200) {
		$paidjson = json_decode($result, true);
        // print json_encode($paidjson); exit();
	} else {
        $redirurl = 'http://127.0.0.1/trigger-app?page=purchase&error=' . urlencode('An error occured, ($httpstatus: '. $httpstatus .') purchase failed. Please file an issue at https://www.github.com/Noitidart/Trigger - and you will get prompt help. ' . $result);
    	header('Location: ' . $redirurl);
        exit();
	}

	// $serial = hash_hmac('sha1', $buy_qty.$buy_qty.$buy_qty, $buy_qty.$mac_hash.$buy_qty, false); // equivalent of CryptoJS.HmacSHA1(buy_qty.toString.repeat(3), buy_qty + '563ee1a8f745e9b3b9bccc2f0994d8d6462e23da' + buy_qty).toString()

    function salt($len) {
    	// salt generator from http://mxr.mozilla.org/mozilla-aurora/source/toolkit/profile/content/createProfileWizard.js?raw=1*/

    	$mozKSaltTable = array(
    		'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
    		'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
    		'1', '2', '3', '4', '5', '6', '7', '8', '9', '0'
    	);

    	$kSaltString = '';
    	for ($i = 0; $i < $len; ++$i) {
    		$kSaltString .= $mozKSaltTable[rand(0, count($mozKSaltTable) - 1)];
    	}
    	return $kSaltString;
    	// return kSaltString + '.' + aName;
    }


    // $serial = base64_encode(hash_hmac('sha1', $buy_qty.$buy_qty.$buy_qty, $buy_qty.$mac_hash.$buy_qty, true)); // changed last arg to true
    // CryptoJS.HmacSHA1(buy_qty.toString.repeat(3), buy_qty + '563ee1a8f745e9b3b9bccc2f0994d8d6462e23da' + buy_qty).toString(CryptoJS.enc.Base64)

    $SALT_LEN = 8;
    $salt = salt($SALT_LEN);
    $serial = base64_encode(hash_hmac('sha1', 'salt_'.$salt, $buy_qty.$mac_hash, true)); // changed last arg to true

    $serial = str_replace('=', '', $serial);
    $serial = str_replace('+', '', $serial);
    $serial = str_replace('/', '', $serial);

    // $oserial = $serial;
    $serial = substr($serial, 0, strlen($serial) - $SALT_LEN) . $salt;

	$query2 = $DB->query('DELETE FROM paypal WHERE confirm_id="' . $confirm_id . '"');


    // receipt
    $ip = $_SERVER['REMOTE_ADDR'];
    $query3 = $DB->query('INSERT INTO receipts (mh, buy_qty, time, ip, serial, paidjson) VALUES ("'. $mac_hash .'", "'. $buy_qty .'", "'. date("Y-m-d H:i:s") .'", "'. $ip .'", "'. $serial .'", "'. urlencode(json_encode($paidjson)) .'")');


	// $redirurl = 'http://127.0.0.1/trigger-app?page=purchase&serial=' . $serial . '&oserial=' . $oserial .'&salt=' . $salt;
	// $redirurl = 'http://127.0.0.1/trigger-app?page=purchase&serial=' . $serial . '&salt=' . $salt;
	$redirurl = 'http://127.0.0.1/trigger-app?page=purchase&serial=' . $serial;
	header('Location: ' . $redirurl);

	// print '<script>setTimeout(function(){window.location.href="'. $redirurl .'"}, 5000)</script>Redirecting in 5 seconds...';
	exit();

?>
